# Generated by Django 4.2.5 on 2023-10-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_task_options_alter_task_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='homepage.task'),
        ),
    ]
